name: minoltimemobile
description: "MinolTime App - control de asistencia inteligente."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  mobile_scanner: ^7.2.0
  http: ^1.2.2
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^10.0.0
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/branding/minoltime_icon_1024x1024.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/branding/minoltime_icon_1024x1024.png"
  adaptive_icon_background: "#7A1FEA"
  adaptive_icon_foreground: "assets/branding/minoltime_icon_1024x1024.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#7A1FEA"
  image: assets/branding/minoltime_icon_1024x1024.png

  android_12:
    color: "#7A1FEA"
    image: assets/branding/minoltime_icon_1024x1024.png

  ios: true
  android: true